# Generated by Django 4.2.6 on 2023-10-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inforLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usg_id', models.CharField(max_length=255)),
                ('usg_network_ip', models.CharField(max_length=255)),
                ('subscriber_mac', models.CharField(max_length=255)),
                ('port_mapping', models.CharField(max_length=255)),
                ('origin_server_url', models.CharField(max_length=255)),
            ],
        ),
    ]
