# Generated by Django 4.2.6 on 2023-10-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inforLoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('passwork', models.CharField(max_length=255)),
            ],
        ),
    ]
